name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  flutter:
    name: Build Flutter App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter 3.22.3 (stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get
        working-directory: flutter_app

      - name: Build Flutter Web
        run: flutter build web --release
        working-directory: flutter_app

      - name: Build Flutter APK
        run: flutter build apk --release --android-skip-build-dependency-validation
        working-directory: flutter_app

      - name: Upload Flutter Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: flutter_app/build/web

      - name: Upload Flutter APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk


  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: flutter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build

      - name: Save Docker Images as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            backend
            nginx