name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  flutter:
    name: Build Flutter App (Web + APK)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter (stable 3.24.3)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Flutter pub get
        run: flutter pub get
        working-directory: flutter_app

      # ---- WEB ----
      - name: Build Flutter Web
        run: flutter build web --release
        working-directory: flutter_app

      # ---- ANDROID APK ----
      - name: Build Flutter APK (Release)
        run: flutter build apk --release --no-android-gradle-daemon --android-skip-build-dependency-validation
        working-directory: flutter_app

      # ---- UPLOAD ARTIFACTS ----
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: flutter_app/build/web

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk



  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: flutter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build

      - name: Save Docker images as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            backend
            nginx